<h1><code ng:non-bindable=""></code>
<div><span class="hint"></span>
</div>
</h1>
<div><div class="using-angularjs-promises-and-umbraco-resources-page"><h3 id="overview">Overview</h3>
<p>Document to outline the way we work with data from the Umbraco rest API which is always returned as a promise, so we in an async way can resolve our data.  </p>
<h3 id="promises-in-umbraco-resources">Promises in Umbraco Resources</h3>
<p>All Umbraco resource methods utilize a helper method:</p>
<pre><code>umbRequestHelper.resourcePromise</code></pre>
<p>This method accepts 2 arguments:</p>
<ul>
<li>The angular HttpPromise which is created with a call to $http.get (post, etc..)</li>
<li>The error message that is bubbled to the UI when the http call fails</li>
</ul>
<p>Here&#39;s an example of the usage in an Umbraco resource. This example is the method of the treeResource that fetches data to display the menu for a tree node:</p>
<pre><code>/** Loads in the data to display the nodes menu */
loadMenu: function (node) {

    return umbRequestHelper.resourcePromise(
        $http.get(getTreeMenuUrl(node)),
        &quot;Failed to retrieve data for a node&#39;s menu &quot; + node.id);
}</code></pre>
<p>HTTP error handling is performed automatically inside of the <code>umbRequestHelper.resourcePromise</code> and inside of Umbraco&#39;s response interceptors.</p>
<h3 id="consuming-umbraco-resources">Consuming Umbraco resources</h3>
<p>When consuming Umbraco resources, a normal angular promise will be returned based on the above <code>umbRequestHelper.resourcePromise</code>. The success callback will always receive the RAW json data from the server and the error callback will always receive an object containing these properties:</p>
<ul>
<li>erroMsg = the error message that can be used to show in the UI</li>
<li>data = the original data object used to create the promise</li>
</ul>
<p>Error handling will be done automatically in the Umbraco resource. Http error handling should not be done during the consumption of an Umbraco resource.</p>
<h4 id="consuming-umbraco-resources_simple-example">Simple example</h4>
<p>An simple example of consuming an Umbraco resource:</p>
<pre><code>treeResource.loadMenu(treeItem.node)
    .then(function(data) {        
        scope.menu = data;
    });</code></pre>
<h4 id="consuming-umbraco-resources_transforming-result-data">Transforming result data</h4>
<p>Sometimes the consumption of an Umbraco resource needs to return a promise itself. This is required in some circumstances such as:</p>
<p>The data from a result of an http resource might need to be transformed into something usable in the UI so a Service may need to call a resource, transform the result and continue to return it&#39;s own promise (since everything happens async).</p>
<p>This is actually very simple to do, the Service (or whatever is consuming the resource) just returns the result of their &#39;then&#39; call. Example - this example is the <code>getActions</code> method of the <code>treeService</code> that consumes the treeResource, transforms the result and continues to return it&#39;s own promise:</p>
<pre><code>getActions: function(treeItem, section) {

    return treeResource.loadMenu(treeItem.node)
        .then(function(data) {
            //need to convert the icons to new ones
            for (var i = 0; i &lt; data.length; i++) {
                data[i].cssclass = iconHelper.convertFromLegacyIcon(data[i].cssclass);
            }
            return data;
        });
} </code></pre>
<p>Notice that this is just returning the call to &#39;then&#39; which will return a promise that resolves the data from it&#39;s return statement.</p>
<h4 id="consuming-umbraco-resources_error-hanlding">Error hanlding</h4>
<p>Ok, what about error handling ? This is really simple as well, we just add an additional method to the .then call. A simple example:</p>
<pre><code>treeResource.loadMenu(treeItem.node)
    .then(function(data) {        
        scope.menu = data;
    }, function(err) {
        //display the error
        notificationsService.error(err.errorMsg);
    });</code></pre>
<h4 id="consuming-umbraco-resources_error-handling-when-transforming-result-data">Error handling when transforming result data</h4>
<p>This is one of those things that is important to note! If you need to return a custom promise based on the result of an Umbraco resource (like the example above in Transforming result data) then you will need to &#39;throw&#39; an error if you want to &#39;bubble&#39; the error to the handler of your custom promise.</p>
<p>The good news is, this is very simple to do, example:</p>
<pre><code>getActions: function(treeItem, section) {

    return treeResource.loadMenu(treeItem.node)
        .then(function(data) {
            //need to convert the icons to new ones
            for (var i = 0; i &lt; data.length; i++) {
                data[i].cssclass = iconHelper.convertFromLegacyIcon(data[i].cssclass);
            }
            return data;
        }, function(err) {
            //display the error
            notificationsService.error(err.errorMsg);

            //since we want the handler of this promise to be notified of this error
            // we just need to rethrow it:
            throw err;
        });
}</code></pre>
<p>The next thing that is important to note is that <strong>you don&#39;t have to do anything</strong> if you don&#39;t want to do anything with the error but still want the error bubbled up to your promises handlers. So for example, if you are expecting the handler of this promise to handle the error and display something in the UI, just leave out the function(err) callback which would look exactly the same as the example for &#39;Transforming result data&#39;</p>
</div></div>
